### ISSUE TITLE
[Bug]: Not Working, no card id created

### ISSUE THREAD

**Issue by cptvincer** [Quorafind/Obsidian-Canvas-Presentation#11]
### Bug Description

Im obsidian 1.1.15 on windows 10, just installed and enabled the plugin, set up some hotkeys... but nothing works.
Ive tried restarting obsidian, tried via command pallet and hotkeys, nothing- the maximum i get is when calling for next or previous a message telling a card needs to be marked first, no slide note found.

Ive tried on new canvas as test, creating some cards or adding some notes- nothing... zoomed out and selected all just to be certain- whats happening is the slide note(id holder) isnt created at all.

Am i missing something?

In the meanwhile is there any way to create a slide note manually? I was dying for this feature to manage a messy very expansive canvas right now, i guess theres some code written in markdown that defines the slide note but i dont know what...

### Obsidian Version

1.1.15

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by CoffeeDrinkRabbit** [comment]
+1

**Comment by fieldrabbit21** [comment]
+1

**Comment by Quorafind** [comment]
Can you take a screenshot of console when you run command

**Comment by ReaderGuy42** [comment]
This happens to me:
![image](https://github.com/Quorafind/Obsidian-Canvas-Presentation/assets/71895400/2fa1c17f-a8e7-440f-883d-264048909094)


Any ideas?

EDIT: Sorry, I think I was still on version 0.0.2 as I think I installed it via BRAT. Installed it through the Market now, and now it works. Thanks :)

**Comment by cptvincer** [comment]
Same, i uninstalled the plugin i had and reinstalled from the community, now all is working! Thanks!
